### ISSUE TITLE
so i am getting this error on my host and idk how to fix it

### ISSUE THREAD

**Issue by Miya25** [ParadiseBotLists/Website#14]
Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.Module._load (/home/runner/node_modules/sqreen/lib/instrumentation/moduleHijacker.js:72:35)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/SparsePristineLight/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.Module._load (/home/runner/SparsePristineLight/node_modules/sqreen/lib/instrumentation/moduleHijacker.js:72:35)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/node_modules/canvas/lib/canvas.js:9:18)

**Comment by Miya25** [comment]
is this a npm error or sqreen
